---
name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Docker Images
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: docker-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            docker-${{ runner.os }}-

      
      - name: Create cache directories
        run: mkdir -p ~/.cache ~/.npm ~/.cache/pip
      
      - name: Cache Linter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: > 
            linter-${{ runner.os }}-${{ hashFiles(
              '**/package-lock.json',
              '**/requirements.txt'
            ) }}
          restore-keys: |
            linter-${{ runner.os }}-

      - name: Run Super-Linter
        uses: github/super-linter@latest
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
